### PR TITLE
Feature/crud client

### PR DESCRIPTION
**Pull request by eduardomrodrigues**
Hi guys! 
My CRUD for our clients is done!
Can you check my code?
Thanks

### CODE REVIEW

**Comment by houspiller** [comment]
and the files with tests?

**Comment by eduardomrodrigues** [comment]
I put them all in tests/routers_test.go

**Comment by marcelorubim** [comment]
Looks good to me! Good work!

Just fix the conflicts and we can merge!

**Comment by eduardomrodrigues** [comment]
I'm on it

**Pull request merged**
